version: 0.2

phases:
  install:
    runtime-versions:
      - nodejs: 10
    commands:
      - npm ci
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run package

artifacts:
  type: zip
  files:
    - packaged.yml

cache:
  paths:
    - "/root/.npm/**/*"
