AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS project to deploy a CDN for hosting static assets in private S3 buckets

Metadata:
  "AWS::ServerlessRepo::Application":
    Name: cloudfront-cdn
    Description: >
      AWS project to deploy a CDN for hosting static assets in private S3 buckets
      Includes: S3 buckets, CloudFront distributions, Route53 record sets
    Author: smoketurner
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["cdn", "cloudfront", "route53", "s3"]
    HomePageUrl: https://github.com/smoketurner/sam-cdn
    SemanticVersion: 2.0.0
    SourceCodeUrl: https://github.com/smoketurner/sam-cdn

  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Domain Configuration"
        Parameters:
          - DomainName
          - HostedZoneId
          - CreateRedirect
          - LogRetentionDays
      - Label:
          default: "API Origin Configuration"
        Parameters:
          - ApiPath
          - ApiOriginDomainName
          - ApiOriginPath
          - ApiOriginKey
      - Label:
          default: "AppSync Origin Configuration"
        Parameters:
          - AppSyncOriginDomainName
    ParameterLabels:
      CreateRedirect:
        default: "Redirect http(s)://www.<DomainName> to https://<DomainName>?"

Parameters:
  DomainName:
    Type: String
    Default: ""
    Description: Optional domain name to use (leave blank for *.cloudfront.net)
  HostedZoneId:
    Type: String
    Description: HostedZoneId for the Domain
    Default: ""
  ApiPath:
    Type: String
    Default: "/api"
    Description: URI path to route to API
  ApiOriginDomainName:
    Type: String
    Default: "api.example.com"
    Description: API origin domain name (set to empty string to disable API origin)
  ApiOriginPath:
    Type: String
    Default: ""
    Description: API origin path (must start with "/")
  ApiOriginKey:
    Type: String
    Default: "NO_API_KEY_SET"
    Description: x-api-key HTTP request header sent to API
  AppSyncOriginDomainName:
    Type: String
    Default: ""
    Description: AppSync origin domain name (will be available at /graphql)
  CreateRedirect:
    Type: String
    Default: "false"
    Description: Set to 'true' to create a CloudFront distribution that redirects https://www.DomainName to https://DomainName
    AllowedValues:
      - "true"
      - "false"
  LogRetentionDays:
    Type: Number
    Default: 30
    Description: Number of days to retain access logs

Conditions:
  HasDomainName: !Not [!Equals [!Ref DomainName, ""]]
  CreateRedirect: !And
    - !Condition HasDomainName
    - !Equals [!Ref CreateRedirect, "true"]
  HasApiOrigin: !Not [!Equals [!Ref ApiOriginDomainName, ""]]
  HasAppSyncOrigin: !Not [!Equals [!Ref AppSyncOriginDomainName, ""]]

Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [!Ref "AWS::Region", "us-east-1"]
        AssertDescription: Region must be us-east-1
  ValidateHostedZone:
    RuleCondition: !Not [!Equals [!Ref DomainName, ""]]
    Assertions:
      - Assert: !Not [!Equals [!Ref HostedZoneId, ""]]
        AssertDescription: HostedZoneId is required if DomainName provided

Resources:
  DefaultIndexFunction:
    Type: "AWS::CloudFront::Function"
    Properties:
      AutoPublish: true
      FunctionCode: |-
        function handler(event) {
          var request = event.request;
          var uri = request.uri;

          // Check whether the URI is missing a file name.
          if (uri.endsWith('/')) {
            request.uri += 'index.html';
          }
          // Check whether the URI is missing a file extension.
          else if (!uri.includes('.')) {
            request.uri += '/index.html';
          }

          return request;
        }
      FunctionConfig:
        Comment: Viewer Request - Default Index
        Runtime: cloudfront-js-1.0
      Name: default_index

  WebSecurityFunction:
    Type: "AWS::CloudFront::Function"
    Properties:
      AutoPublish: true
      FunctionCode: |-
        function handler(event) {
          var response = event.response;
          var headers = response.headers;

          var policies = [
            'autoplay none',
            'camera none',
            'fullscreen self',
            'geolocation none',
            'gyroscope none',
            'magnetometer none',
            'midi none',
            'microphone none',
            'notifications none',
            'payment none',
            'push none',
            'speaker self',
            'sync-xhr none',
            'vibrate none'
          ];

          headers['strict-transport-security'] = {
            value: 'max-age=63072000; includeSubDomains; preload'
          };
          headers['content-security-policy'] = {
            value: "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'"
          };
          headers['x-content-type-options'] = {
            value: 'nosniff'
          };
          headers['referrer-policy'] = {
            value: 'strict-origin-when-cross-origin'
          };
          headers['feature-policy'] = {
            value: policies.join('; ')
          };
          headers['x-frame-options'] = {
            value: 'DENY'
          };
          headers['x-xss-protection'] = {
            value: '1; mode=block'
          };

          // opt-out of Google Chrome's FLoC
          // @see https://plausible.io/blog/google-floc#how-to-opt-out-of-floc-as-a-web-developer-set-a-permissions-policy
          headers['permissions-policy'] = {
            value: 'interest-cohort=()'
          };

          return response;
        }
      FunctionConfig:
        Comment: Viewer Response - Web Security
        Runtime: cloudfront-js-1.0
      Name: web_security

  WebCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Condition: HasDomainName
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - !If
          - CreateRedirect
          - DomainName: !Sub "www.${DomainName}"
            HostedZoneId: !Ref HostedZoneId
          - !Ref "AWS::NoValue"
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Ref DomainName

  LogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            ExpirationInDays: !Ref LogRetentionDays
            Id: RetentionRule
            NoncurrentVersionExpirationInDays: !Ref LogRetentionDays
            Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName} Logs"
      VersioningConfiguration:
        Status: Suspended

  WebBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !If
        - HasDomainName
        - !Ref DomainName
        - !Sub "web-${AWS::AccountId}-${AWS::Region}"
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: !If
          - HasDomainName
          - !Sub "AWSLogs/${AWS::AccountId}/S3/${DomainName}/"
          - !Sub "AWSLogs/${AWS::AccountId}/S3/web-${AWS::AccountId}-${AWS::Region}/"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !If
            - HasDomainName
            - !Ref DomainName
            - !Sub "web-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

  WebBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: "s3:GetObject"
            Resource: !Sub "${WebBucket.Arn}/*"
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${WebBucket.Arn}/*"
              - !GetAtt WebBucket.Arn
            Condition:
              Bool:
                "aws:SecureTransport": "false"

  RedirectBucket:
    Type: "AWS::S3::Bucket"
    Condition: CreateRedirect
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref WebBucket
          Protocol: https
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "www.${DomainName}"

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases: !If
          - HasDomainName
          - - !Ref DomainName
          - !Ref "AWS::NoValue"
        CacheBehaviors:
          - !If
            - HasApiOrigin
            - AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - PATCH
                - POST
                - DELETE
              # CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad" # Managed-CachingDisabled
              Compress: true
              ForwardedValues:
                Headers:
                  - Accept
                  - Authorization
                  - Content-Type
                  - Origin
                  - Referer
                QueryString: true
              MaxTTL: 0
              MinTTL: 0
              DefaultTTL: 0
              # Can't use Managed-AllViewer because it sends the Host header
              # OriginRequestPolicyId: "216adef6-5c7f-47e4-b989-5492eafa07d3" # Managed-AllViewer
              PathPattern: !Sub "${ApiPath}*"
              TargetOriginId: api
              ViewerProtocolPolicy: redirect-to-https
            - !Ref "AWS::NoValue"
          - !If
            - HasAppSyncOrigin
            - AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - PATCH
                - POST
                - DELETE
              # CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad" # Managed-CachingDisabled
              Compress: true
              ForwardedValues:
                Headers:
                  - Accept
                  - Authorization
                  - Content-Type
                  - Origin
                  - Referer
                QueryString: true
              MaxTTL: 0
              MinTTL: 0
              DefaultTTL: 0
              # Can't use Managed-AllViewer because it sends the Host header
              # OriginRequestPolicyId: "216adef6-5c7f-47e4-b989-5492eafa07d3" # Managed-AllViewer
              PathPattern: "/graphql*"
              TargetOriginId: appsync
              ViewerProtocolPolicy: redirect-to-https
            - !Ref "AWS::NoValue"
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: "/index.html"
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # Managed-CachingOptimized
          Compress: true
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !Sub "arn:aws:cloudfront::${AWS::AccountId}:function/${DefaultIndexFunction}"
            - EventType: viewer-response
              FunctionARN: !Sub "arn:aws:cloudfront::${AWS::AccountId}:function/${WebSecurityFunction}"
          OriginRequestPolicyId: "acba4595-bd28-49b8-b9fe-13317c0390fa" # Managed-UserAgentRefererHeaders
          TargetOriginId: s3
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Logging:
          Bucket: !GetAtt LogBucket.DomainName
          IncludeCookies: false
          Prefix: !Sub "AWSLogs/${AWS::AccountId}/CloudFront/"
        Origins:
          - !If
            - HasApiOrigin
            - Id: api
              ConnectionAttempts: 3 # default
              ConnectionTimeout: 10 # seconds
              DomainName: !Ref ApiOriginDomainName
              OriginPath: !Ref ApiOriginPath
              OriginCustomHeaders:
                - HeaderName: "x-api-key"
                  HeaderValue: !Ref ApiOriginKey
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - "TLSv1.2"
            - !Ref "AWS::NoValue"
          - !If
            - HasAppSyncOrigin
            - Id: appsync
              ConnectionAttempts: 3 # default
              ConnectionTimeout: 10 # seconds
              DomainName: !Ref AppSyncOriginDomainName
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - "TLSv1.2"
            - !Ref "AWS::NoValue"
          - Id: s3
            ConnectionAttempts: 3 # default
            ConnectionTimeout: 10 # seconds
            DomainName: !GetAtt WebBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        PriceClass: PriceClass_100
        ViewerCertificate: !If
          - HasDomainName
          - AcmCertificateArn: !Ref WebCertificate
            MinimumProtocolVersion: TLSv1.2_2019
            SslSupportMethod: sni-only
          - CloudFrontDefaultCertificate: true

  RedirectCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Condition: CreateRedirect
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "www.${DomainName}"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # Managed-CachingOptimized
          Compress: true
          OriginRequestPolicyId: "acba4595-bd28-49b8-b9fe-13317c0390fa" # Managed-UserAgentRefererHeaders
          TargetOriginId: s3
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - Id: s3
            ConnectionAttempts: 3 # default
            ConnectionTimeout: 10 # seconds
            DomainName: !Sub "${RedirectBucket}.s3-website-${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: http-only # private bucket access only works over HTTP
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref WebCertificate
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only

  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "CloudFront OAI"

  WebRecordSetGroup:
    Type: "AWS::Route53::RecordSetGroup"
    Condition: HasDomainName
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - AliasTarget:
            DNSName: !GetAtt CloudFrontDistribution.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
          Name: !Ref DomainName
          Type: A
        - AliasTarget:
            DNSName: !GetAtt CloudFrontDistribution.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
          Name: !Ref DomainName
          Type: AAAA

  RedirectRecordSetGroup:
    Type: "AWS::Route53::RecordSetGroup"
    Condition: CreateRedirect
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - AliasTarget:
            DNSName: !GetAtt RedirectCloudFrontDistribution.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
          Name: !Sub "www.${DomainName}"
          Type: A
        - AliasTarget:
            DNSName: !GetAtt RedirectCloudFrontDistribution.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
          Name: !Sub "www.${DomainName}"
          Type: AAAA

Outputs:
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
  CloudFrontDomainName:
    Description: CloudFront Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
  CertificateArn:
    Description: SSL Certficate ARN
    Value: !Ref WebCertificate
    Condition: HasDomainName
  WebBucketName:
    Description: Web S3 Bucket Name
    Value: !Ref WebBucket
  WebBucketArn:
    Description: Web S3 Bucket ARN
    Value: !GetAtt WebBucket.Arn
  WebBucketDomainName:
    Description: Web S3 Bucket Domain Name
    Value: !GetAtt WebBucket.RegionalDomainName
  LogBucketName:
    Description: Log S3 Bucket Name
    Value: !Ref LogBucket
  LogBucketArn:
    Description: Log S3 Bucket ARN
    Value: !GetAtt LogBucket.Arn
  LogBucketDomainName:
    Description: Log S3 Bucket Domain Name
    Value: !GetAtt LogBucket.RegionalDomainName
